import Foundation

#if !Xcode
extension LocalizedStringResource {
  static let mainWindowCloneAction = LocalizedStringResource("main_window.clone.action", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCloneNewName = LocalizedStringResource("main_window.clone.new_name", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCloneTitle = LocalizedStringResource("main_window.clone.title", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCommonApp = LocalizedStringResource("main_window.common.app", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCommonBundle = LocalizedStringResource("main_window.common.bundle", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCommonBundleId = LocalizedStringResource("main_window.common.bundle_id", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCommonCancel = LocalizedStringResource("main_window.common.cancel", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCommonDevice = LocalizedStringResource("main_window.common.device", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCommonName = LocalizedStringResource("main_window.common.name", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCommonNotAvailable = LocalizedStringResource("main_window.common.not_available", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCommonPath = LocalizedStringResource("main_window.common.path", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCommonPhone = LocalizedStringResource("main_window.common.phone", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCommonSandbox = LocalizedStringResource("main_window.common.sandbox", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCommonSimulator = LocalizedStringResource("main_window.common.simulator", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCommonState = LocalizedStringResource("main_window.common.state", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCommonTarget = LocalizedStringResource("main_window.common.target", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCommonUdid = LocalizedStringResource("main_window.common.udid", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCommonWatch = LocalizedStringResource("main_window.common.watch", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCreateAction = LocalizedStringResource("main_window.create.action", bundle: .atURL(Bundle.module.bundleURL))
  static func mainWindowCreateCompatibleDeviceTypesCount(count: Int) -> LocalizedStringResource {
    LocalizedStringResource("main_window.create.compatible_device_types_count", defaultValue: "\(count) compatible device types", bundle: .atURL(Bundle.module.bundleURL))
  }
  static let mainWindowCreateDeviceType = LocalizedStringResource("main_window.create.device_type", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCreateNoRuntime = LocalizedStringResource("main_window.create.no_runtime", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCreateRuntime = LocalizedStringResource("main_window.create.runtime", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCreateTitle = LocalizedStringResource("main_window.create.title", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowCreateUnreportedCompatibility = LocalizedStringResource("main_window.create.unreported_compatibility", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowDeleteAction = LocalizedStringResource("main_window.delete.action", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowDeleteMessage = LocalizedStringResource("main_window.delete.message", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowDeleteTitle = LocalizedStringResource("main_window.delete.title", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowEraseAction = LocalizedStringResource("main_window.erase.action", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowEraseMessage = LocalizedStringResource("main_window.erase.message", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowEraseTitle = LocalizedStringResource("main_window.erase.title", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowInstallAppAction = LocalizedStringResource("main_window.install_app.action", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowInstallAppLaunchAfterInstall = LocalizedStringResource("main_window.install_app.launch_after_install", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowInstallAppTitle = LocalizedStringResource("main_window.install_app.title", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowPairAction = LocalizedStringResource("main_window.pair.action", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowPairPhoneUdid = LocalizedStringResource("main_window.pair.phone_udid", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowPairSelectedDevices = LocalizedStringResource("main_window.pair.selected_devices", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowPairTitle = LocalizedStringResource("main_window.pair.title", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowPairWatchUdid = LocalizedStringResource("main_window.pair.watch_udid", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowRenameAction = LocalizedStringResource("main_window.rename.action", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowRenameTitle = LocalizedStringResource("main_window.rename.title", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowResetSandboxAction = LocalizedStringResource("main_window.reset_sandbox.action", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowResetSandboxMessage = LocalizedStringResource("main_window.reset_sandbox.message", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowResetSandboxTitle = LocalizedStringResource("main_window.reset_sandbox.title", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowUninstallAppAction = LocalizedStringResource("main_window.uninstall_app.action", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowUninstallAppMessage = LocalizedStringResource("main_window.uninstall_app.message", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowUninstallAppTitle = LocalizedStringResource("main_window.uninstall_app.title", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowUnpairAction = LocalizedStringResource("main_window.unpair.action", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowUnpairMessage = LocalizedStringResource("main_window.unpair.message", bundle: .atURL(Bundle.module.bundleURL))
  static let mainWindowUnpairTitle = LocalizedStringResource("main_window.unpair.title", bundle: .atURL(Bundle.module.bundleURL))
}
#endif
